In [212]:
import pandas as pd
import numpy as np

In [213]:
df= pd.read_csv('customer_shopping.csv')         
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [214]:
df1=pd.read_csv('Sales.csv')
df1

,Order_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Discount,Payment_Mode,Sales_Channel,Order_Status
0,O0001,2025-09-18,C079,P024,S002,6,0.20,Cash,Store,Completed
1,O0002,2025-12-08,C137,P017,S010,6,0.10,Bank Transfer,Distributor,Completed
2,O0003,2024-01-14,C108,P017,S014,7,0.20,Cash,Online,Returned
3,O0004,2024-12-30,C008,P004,S008,4,0.05,Bank Transfer,Distributor,Returned
4,O0005,2025-04-29,C041,P014,S017,4,0.10,UPI,Distributor,Completed
...,...,...,...,...,...,...,...,...,...,...
195,O0196,2024-08-17,C023,P015,S011,8,0.00,Bank Transfer,Online,Completed
196,O0197,2025-02-08,C097,P016,S013,5,0.10,Bank Transfer,Distributor,Returned
197,O0198,2025-06-07,C062,P016,S014,2,0.15,Bank Transfer,Distributor,Returned
198,O0199,2025-12-21,C016,P007,S030,5,0.05,Credit Card,Store,Completed
199,O0200,2025-12-23,C148,P014,S023,7,0.00,Credit Card,Store,Completed

In [215]:
dfp=pd.read_csv('Products.csv')
dfp.head()

  Product_ID Product_Name     Category Sub_Category  Unit_Price      Cost
0       P001       Laptop  Electronics        Basic         150     89.28
1       P002      Monitor  Electronics        Basic         800    536.55
2       P003     Keyboard  Electronics        Basic        1200    730.48
3       P004        Mouse  Electronics        Basic         150    106.88
4       P005       Webcam  Electronics      Premium       35000  23776.85

In [216]:

df2=pd.read_csv('Salespersons.csv')
df2.head()

  Salesperson_ID Salesperson_Name            Department Region
0           S001      Rahul Yadav                 Sales   West
1           S002     Kavita Kumar      Enterprise Sales   East
2           S003       Amit Yadav      Enterprise Sales   East
3           S004      Arjun Verma      Enterprise Sales  North
4           S005      Vikas Verma  Business Development   East

In [217]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [218]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [219]:
df["Review Rating"]=df["Review Rating"].fillna(df["Review Rating"].mean(), inplace=True)
df["Review Rating"].isnull().sum()

C:\Users\Victus\AppData\Local\Temp\ipykernel_25524\4051365171.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Review Rating"]=df["Review Rating"].fillna(df["Review Rating"].mean(), inplace=True)

np.int64(0)

In [220]:
df.columns=df.columns.str.replace(" ","_")
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Promo_Code_Used', 'Previous_Purchases',
       'Payment_Method', 'Frequency_of_Purchases'],
      dtype='str')

In [221]:
pip install psycopg2-binary sqlalchemy pymysql

Requirement already satisfied: psycopg2-binary in c:\Users\Victus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\Users\Victus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Requirement already satisfied: pymysql in c:\Users\Victus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\Users\Victus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Victus\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [222]:

from sqlalchemy import create_engine
import urllib.parse

# write database connection code below using mysql
username = 'root'
raw_password = 'Password@2026'
host = 'localhost'
port = '3306'
database = 'shopping'

# Safe-encode the password to handle the '@' symbol safely
password = urllib.parse.quote_plus(raw_password)

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')
table_name = 'Products'
dfp.to_sql(table_name, con=engine, if_exists='replace', index=False)

print(f"DataFrame has been written to the '{table_name}' table in the '{database}' database.")

DataFrame has been written to the 'Products' table in the 'shopping' database.

C:\Users\Victus\AppData\Local\Temp\ipykernel_25524\637004038.py:16: UserWarning: The provided table name 'Products' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  dfp.to_sql(table_name, con=engine, if_exists='replace', index=False)