In [125]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

In [126]:
df=pd.read_csv("customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [128]:

df.columns
df.columns=df.columns.str.replace(' ',"_")
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Promo_Code_Used', 'Previous_Purchases',
       'Payment_Method', 'Frequency_of_Purchases'],
      dtype='str')

In [129]:
df.rename(columns={"Purchase_Amount_(USD)":"Purchase_Amount"},inplace=True)
df

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount,Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [130]:
#create column age_group based on age
labels = ['Young Adults','Adult','Middle Aged', 'Senior']
df['age_group'] = pd.qcut(df['Age'], q=4, labels=labels)

In [131]:
df[['Age','age_group']].head(10)

   Age     age_group
0   55   Middle Aged
1   19  Young Adults
2   50   Middle Aged
3   21  Young Adults
4   45   Middle Aged
5   46   Middle Aged
6   63        Senior
7   27  Young Adults
8   26  Young Adults
9   57   Middle Aged

In [132]:
#create column purchase_Frequency_days
df.columns = df.columns.str.lower()
df.columns
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'every 3 months': 90,
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [133]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [134]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [135]:
df[["discount_applied","promo_code_used"]].head(5)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [136]:
(df["promo_code_used"]==df["discount_applied"]).all()
df=df.drop('promo_code_used', axis=1)

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [137]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\Users\Victus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\Users\Victus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\Users\Victus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Victus\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [138]:
from sqlalchemy import create_engine
import urllib.parse
username= 'root'
raw_password= 'Password@2026'
host= 'localhost'
port= '3306'
database='shopping'
password = urllib.parse.quote_plus(raw_password)
engine =  create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
table_name = 'customer_shopping_behavior'
df.to_sql(table_name, con=engine, if_exists='replace', index=False)
print(f'database {database} created successfully in table {table_name} in mysql server')

database shopping created successfully in table customer_shopping_behavior in mysql server