In [59]:
import numpy as np
import pandas as pd

In [60]:
arr=np.array([1,2,3,4])
print(arr)
data={"name":["suman"],"age":[30]}
df=pd.DataFrame(data)
print(df)

[1 2 3 4]
    name  age
0  suman   30

In [61]:
cust=pd.read_csv("Customers.csv")
cust

    Customer_ID Customer_Name  Gender         City Region Customer_Segment
0          C001  Anjali Kumar    Male      Gurgaon  North   Small Business
1          C002  Kavita Kumar  Female        Patna   East        Corporate
2          C003    Rahul Jain    Male       Mumbai   West        Corporate
3          C004  Pooja Sharma  Female       Jaipur  North         Consumer
4          C005   Rohan Yadav  Female  Bhubaneswar   East   Small Business
..          ...           ...     ...          ...    ...              ...
145        C146   Rahul Kumar  Female      Kolkata   East        Corporate
146        C147   Arjun Yadav  Female         Pune   West   Small Business
147        C148   Anjali Jain    Male        Delhi  North   Small Business
148        C149     Neha Jain    Male      Chennai  South         Consumer
149        C150   Vikas Verma    Male  Bhubaneswar   East        Corporate

[150 rows x 6 columns]

In [62]:
cust[cust.Customer_Name.duplicated()]

    Customer_ID Customer_Name  Gender         City Region Customer_Segment
25         C026   Priya Joshi    Male    Bengaluru  South   Small Business
26         C027   Arjun Joshi  Female    Bengaluru  South   Small Business
30         C031    Pooja Jain    Male      Kolkata   East   Small Business
31         C032    Vikas Jain  Female         Pune   West   Small Business
34         C035  Pooja Sharma    Male    Ahmedabad   West   Small Business
..          ...           ...     ...          ...    ...              ...
143        C144   Pooja Singh    Male    Ahmedabad   West        Corporate
144        C145   Pooja Kumar    Male  Bhubaneswar   East         Consumer
145        C146   Rahul Kumar  Female      Kolkata   East        Corporate
146        C147   Arjun Yadav  Female         Pune   West   Small Business
147        C148   Anjali Jain    Male        Delhi  North   Small Business

[70 rows x 6 columns]

In [64]:
cust["Customer_Name"].duplicated().value_counts()

Customer_Name
False    80
True     70
Name: count, dtype: int64

In [ ]:
product=pd.read_csv("Products.csv")
product.head()

  Product_ID Product_Name     Category Sub_Category  Unit_Price      Cost
0       P001       Laptop  Electronics        Basic         150     89.28
1       P002      Monitor  Electronics        Basic         800    536.55
2       P003     Keyboard  Electronics        Basic        1200    730.48
3       P004        Mouse  Electronics        Basic         150    106.88
4       P005       Webcam  Electronics      Premium       35000  23776.85

In [ ]:
sales=pd.read_csv("Sales.csv")
sales.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Salesperson_ID,Quantity,Discount,Payment_Mode,Sales_Channel,Order_Status
0,O0001,2025-09-18,C079,P024,S002,6,0.20,Cash,Store,Completed
1,O0002,2025-12-08,C137,P017,S010,6,0.10,Bank Transfer,Distributor,Completed
2,O0003,2024-01-14,C108,P017,S014,7,0.20,Cash,Online,Returned
3,O0004,2024-12-30,C008,P004,S008,4,0.05,Bank Transfer,Distributor,Returned
4,O0005,2025-04-29,C041,P014,S017,4,0.10,UPI,Distributor,Completed

In [ ]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        200 non-null    str
 1   Order_Date      200 non-null    str
 2   Customer_ID     200 non-null    str
 3   Product_ID      200 non-null    str
 4   Salesperson_ID  200 non-null    str
 5   Quantity        200 non-null    int64
 6   Discount        200 non-null    float64
 7   Payment_Mode    200 non-null    str
 8   Sales_Channel   200 non-null    str
 9   Order_Status    200 non-null    str
dtypes: float64(1), int64(1), str(8)
memory usage: 15.8 KB

In [ ]:
sales.describe()

         Quantity    Discount
count  200.000000  200.000000
mean     4.535000    0.098750
std      2.214338    0.069354
min      1.000000    0.000000
25%      3.000000    0.050000
50%      5.000000    0.100000
75%      6.000000    0.150000
max      8.000000    0.200000

In [ ]:
sales.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Salesperson_ID    0
Quantity          0
Discount          0
Payment_Mode      0
Sales_Channel     0
Order_Status      0
dtype: int64

In [ ]:
#sales[sales[sales.duplicated()]]

In [ ]:
sales.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Salesperson_ID',
       'Quantity', 'Discount', 'Payment_Mode', 'Sales_Channel',
       'Order_Status'],
      dtype='str')

In [ ]:
sales.columns=sales.columns.str.replace(" ","_")
sales.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Salesperson_ID',
       'Quantity', 'Discount', 'Payment_Mode', 'Sales_Channel',
       'Order_Status'],
      dtype='str')

In [67]:
super=pd.read_csv("Salespersons.csv")
super.head()

  Salesperson_ID Salesperson_Name            Department Region
0           S001      Rahul Yadav                 Sales   West
1           S002     Kavita Kumar      Enterprise Sales   East
2           S003       Amit Yadav      Enterprise Sales   East
3           S004      Arjun Verma      Enterprise Sales  North
4           S005      Vikas Verma  Business Development   East

In [80]:
super["Salesperson_Name"].value_counts()
super["Salesperson_Name"].duplicated().sum()
#super["Salesperson_Name"].count()
super["Salesperson_Name"].nunique()

29